src/Entity/Prescription.php
<?php

namespace App\Entity;

use App\Repository\PrescriptionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PrescriptionRepository::class)]
class Prescription
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'prescriptions')]
    private ?Medecin $medecin = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateFin = null;

    #[ORM\ManyToOne(inversedBy: 'prescriptions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $patient = null;

    #[ORM\Column(nullable: true)]
    private ?array $medicaments = null;

    #[ORM\OneToOne(inversedBy: 'prescription', cascade: ['persist', 'remove'])]
    private ?AvisMedecin $avis_medecin = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMedecin(): ?Medecin
    {
        return $this->medecin;
    }

    public function setMedecin(?Medecin $medecin): static
    {
        $this->medecin = $medecin;

        return $this;
    }

    public function getPatient(): ?Utilisateur
    {
        return $this->patient;
    }

    public function setPatient(?Utilisateur $patient): static
    {
        $this->patient = $patient;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): static
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): static
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getMedicaments(): ?array
    {
        return $this->medicaments;
    }

    public function setMedicaments(?array $medicaments): static
    {
        $this->medicaments = $medicaments;

        return $this;
    }

    public function getAvisMedecin(): ?AvisMedecin
    {
        return $this->avis_medecin;
    }

    public function setAvisMedecin(?AvisMedecin $avis_medecin): static
    {
        $this->avis_medecin = $avis_medecin;

        return $this;
    }

}

templates/user/dashboard.html.twig
{# templates/sejour/list.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Liste des séjours{% endblock %}
    
{% block content %}
   <h1>Liste des séjours</h1>
   <br>

{% set currentSejours = [] %}
{% set upcomingSejours = [] %}
{% set pastSejours = [] %}

{% for sejour in sejours %}
    {% if sejour.dateDebut <= "now" and sejour.dateFin >= "now" %}
        {% set currentSejours = currentSejours|merge([sejour]) %}
    {% elseif sejour.dateDebut > "now" %}
        {% set upcomingSejours = upcomingSejours|merge([sejour]) %}
    {% else %}
        {% set pastSejours = pastSejours|merge([sejour]) %}
    {% endif %}
{% endfor %}

{% if sejours is empty %}
        <p>Aucun séjour trouvé.</p>
    {% else %}
<table class="table">
    <thead>
        <tr>
            <th>Date de début</th>
            <th>Date de fin</th>
            <th>Motif</th>
            <th>Spécialité nécessaire</th>
            <th>Statut</th>
        </tr>
    </thead>
    <tbody>
        {% if currentSejours %}
            <tr><th colspan="5" style="background-color: lightblue;">Séjour en cours</th></tr>
            {% for sejour in currentSejours %}
                <tr>
                    <td>{{ sejour.dateDebut|date('d/m/Y') }}</td>
                    <td>{{ sejour.dateFin|date('d/m/Y') }}</td>
                    <td>{{ sejour.motif }}</td>
                    <td>{{ sejour.specialiteNecessaire }}</td>
                    <td>En cours</td>
                </tr>
            {% endfor %}
        {% endif %}
        
        {% if upcomingSejours %}
            <tr><th colspan="5" style="background-color: lightblue;">Séjours à venir</th></tr>
            {% for sejour in upcomingSejours %}
                <tr>
                    <td>{{ sejour.dateDebut|date('d/m/Y') }}</td>
                    <td>{{ sejour.dateFin|date('d/m/Y') }}</td>
                    <td>{{ sejour.motif }}</td>
                    <td>{{ sejour.specialiteNecessaire }}</td>
                    <td>À venir</td>
                </tr>
            {% endfor %}
        {% endif %}
        
        {% if pastSejours %}
            <tr><th colspan="5" style="background-color: lightblue;">Séjours passés</th></tr>
            {% for sejour in pastSejours %}
                <tr>
                    <td>{{ sejour.dateDebut|date('d/m/Y') }}</td>
                    <td>{{ sejour.dateFin|date('d/m/Y') }}</td>
                    <td>{{ sejour.motif }}</td>
                    <td>{{ sejour.specialiteNecessaire }}</td>
                    <td>Passé</td>
                </tr>
            {% endfor %}
        {% endif %}
    </tbody>
</table>
 {% endif %}
{% endblock %}

templates/user/dossier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dossier de {{ user.nom|upper }} {{ user.prenom|capitalize }} {% endblock %}

{% block content %}
    <h1>Dossier de {{ user.nom|upper }} {{ user.prenom|capitalize }}</h1>
    <hr>
    <h3>Informations personnelles</h3>
    <hr>
    <div class="row">
    <div class="col-md-6">
    <p><b>{{ user.nom|upper }} {{ user.prenom|capitalize }}</b></p>
    <p>Email : <b>{{ user.email }}</b></p>
    <p>Adresse : <b>{{ user.adresse }}</b></p>
    </div>
    </div>
    <hr>
    <h3>Liste des séjours</h3>
    <br>
    {% if sejours is empty %}
        <p>Aucun séjour trouvé.</p>
    {% else %}
        <table class="table">
            <thead>
                <tr>
                    <th>Date de début</th>
                    <th>Date de fin</th>
                    <th>Motif</th>
                    <th>Médecin</th>
                </tr>
            </thead>
            <tbody>
                {% for sejour in sejours %}
                    <tr>
                        <td>{{ sejour.dateDebut|date('d/m/Y') }}</td>
                        <td>{{ sejour.dateFin|date('d/m/Y') }}</td>
                        <td>{{ sejour.motif }}</td>
                        <td>Dr. {{ sejour.medecin.nom|upper }} - {{ sejour.medecin.specialite }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
    {% endif %}
    <h3>Prescriptions et avis du médecin</h3>
    <hr>
    {% if prescriptions is empty %}
        <p>Aucune prescription ni avis à ce jour.</p>
    {% else %}
<table class="table">
    <thead>
        <tr>
            <th>Date de début</th>
            <th>Date de fin</th>
            <th>Médicaments</th>
            <th>Avis Médical</th>
            <th>Médecin</th>
        </tr>
    </thead>
    <tbody>
        {% for prescription in prescriptions %}
        <tr>
            <td>{{ prescription.dateDebut|date('d/m/Y') }}</td>
            <td>{{ prescription.dateFin|date('d/m/Y') }}</td>
            <td>
                {% if prescription.medicaments is not empty %}
                <ul>
                    {% for medicament in prescription.medicaments %}
                    <li>{{ medicament.libelle }} - {{ medicament.posologie }}</li>
                    {% endfor %}
                </ul>
                {% else %}
                None
                {% endif %}
            </td>
            <td>
                {% if prescription.avisMedecin %}
                <strong>Libellé:</strong> {{ prescription.avisMedecin.libelle }}<br>
                <strong>Date:</strong> {{ prescription.avisMedecin.date|date('d/m/Y') }}<br>
                <strong>Description:</strong> {{ prescription.avisMedecin.description }}
                {% else %}
                None
                {% endif %}
            </td>
            <td>Dr. {{ prescription.medecin.nom|upper }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
    <hr>
    
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des dossiers patients{% endblock %}

{% block content %}

<h1>Liste des dossiers patients</h1>
<br>
<table class="table">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Email</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
            {% if 'ROLE_VISITEUR' in user.roles and 'ROLE_ADMIN' not in user.roles %}
            <tr>
                <td>{{ user.nom|upper }} {{ user.prenom|capitalize }}</td>
                <td>{{ user.email }}</td>
                <td><a href="{{ path('user_show', {'id': user.id}) }}" class="btn btn-info" style="padding-top:3px;padding-bottom:3px;">Consulter le dossier</a></td>
            </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>

{% endblock %}